//
//  Assets.swift
//  SA bot
//
//  Created by Kyle Bashour on 4/17/15.
//  Copyright (c) 2015 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class Assets : NSObject {

    //// Cache

    private struct Cache {
        static var red: UIColor = UIColor(red: 0.902, green: 0.056, blue: 0.258, alpha: 1.000)
        static var lightGrey: UIColor = UIColor(red: 0.729, green: 0.769, blue: 0.788, alpha: 1.000)
        static var imageOfScheduletabselected: UIImage?
        static var scheduletabselectedTargets: [AnyObject]?
        static var imageOfScheduletabgrey: UIImage?
        static var scheduletabgreyTargets: [AnyObject]?
        static var imageOfPrintertabselected: UIImage?
        static var printertabselectedTargets: [AnyObject]?
        static var imageOfPrintertabgrey: UIImage?
        static var printertabgreyTargets: [AnyObject]?
        static var imageOfRedstatus: UIImage?
        static var redstatusTargets: [AnyObject]?
        static var imageOfYellowstatus: UIImage?
        static var yellowstatusTargets: [AnyObject]?
        static var imageOfGreenstatus: UIImage?
        static var greenstatusTargets: [AnyObject]?
        static var imageOfGreystatus: UIImage?
        static var greystatusTargets: [AnyObject]?
    }

    //// Colors

    public class var red: UIColor { return Cache.red }
    public class var lightGrey: UIColor { return Cache.lightGrey }

    //// Drawing Methods

    public class func drawScheduletabselected() {
        //// Color Declarations
        let color = UIColor(red: 0.969, green: 0.498, blue: 0.000, alpha: 1.000)

        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(6, 5))
        bezierPath.addLineToPoint(CGPointMake(8, 5))
        bezierPath.addLineToPoint(CGPointMake(8, 0))
        bezierPath.addLineToPoint(CGPointMake(6, 0))
        bezierPath.addLineToPoint(CGPointMake(6, 5))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(18, 5))
        bezierPath.addLineToPoint(CGPointMake(20, 5))
        bezierPath.addLineToPoint(CGPointMake(20, 0))
        bezierPath.addLineToPoint(CGPointMake(18, 0))
        bezierPath.addLineToPoint(CGPointMake(18, 5))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(23, 9))
        bezierPath.addLineToPoint(CGPointMake(3, 9))
        bezierPath.addLineToPoint(CGPointMake(3, 23))
        bezierPath.addLineToPoint(CGPointMake(23, 23))
        bezierPath.addLineToPoint(CGPointMake(23, 9))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(5, 2))
        bezierPath.addCurveToPoint(CGPointMake(5, 5), controlPoint1: CGPointMake(5, 2), controlPoint2: CGPointMake(5, 5))
        bezierPath.addCurveToPoint(CGPointMake(6, 6), controlPoint1: CGPointMake(5, 5), controlPoint2: CGPointMake(5.25, 5.75))
        bezierPath.addCurveToPoint(CGPointMake(8, 6), controlPoint1: CGPointMake(6.75, 6.25), controlPoint2: CGPointMake(7.25, 6.25))
        bezierPath.addCurveToPoint(CGPointMake(9, 5), controlPoint1: CGPointMake(8.75, 5.75), controlPoint2: CGPointMake(9, 5))
        bezierPath.addLineToPoint(CGPointMake(9, 2))
        bezierPath.addLineToPoint(CGPointMake(17, 2))
        bezierPath.addLineToPoint(CGPointMake(17, 5))
        bezierPath.addCurveToPoint(CGPointMake(18, 6), controlPoint1: CGPointMake(17, 5), controlPoint2: CGPointMake(17.25, 5.75))
        bezierPath.addCurveToPoint(CGPointMake(19.05, 6.19), controlPoint1: CGPointMake(18.39, 6.13), controlPoint2: CGPointMake(19.05, 6.19))
        bezierPath.addCurveToPoint(CGPointMake(20, 6), controlPoint1: CGPointMake(19.05, 6.19), controlPoint2: CGPointMake(19.64, 6.12))
        bezierPath.addCurveToPoint(CGPointMake(21, 5), controlPoint1: CGPointMake(20.75, 5.75), controlPoint2: CGPointMake(21, 5))
        bezierPath.addLineToPoint(CGPointMake(21, 2))
        bezierPath.addLineToPoint(CGPointMake(22, 2))
        bezierPath.addCurveToPoint(CGPointMake(25, 3), controlPoint1: CGPointMake(22, 2), controlPoint2: CGPointMake(24, 2))
        bezierPath.addCurveToPoint(CGPointMake(26, 6), controlPoint1: CGPointMake(26, 4), controlPoint2: CGPointMake(26, 6))
        bezierPath.addLineToPoint(CGPointMake(26, 23))
        bezierPath.addCurveToPoint(CGPointMake(25, 25), controlPoint1: CGPointMake(26, 23), controlPoint2: CGPointMake(25.75, 24.25))
        bezierPath.addCurveToPoint(CGPointMake(23, 26), controlPoint1: CGPointMake(24.25, 25.75), controlPoint2: CGPointMake(23, 26))
        bezierPath.addLineToPoint(CGPointMake(3, 26))
        bezierPath.addCurveToPoint(CGPointMake(1, 25), controlPoint1: CGPointMake(3, 26), controlPoint2: CGPointMake(1.75, 25.75))
        bezierPath.addCurveToPoint(CGPointMake(0, 23), controlPoint1: CGPointMake(0.25, 24.25), controlPoint2: CGPointMake(0, 23))
        bezierPath.addLineToPoint(CGPointMake(0, 6))
        bezierPath.addCurveToPoint(CGPointMake(1, 3), controlPoint1: CGPointMake(0, 6), controlPoint2: CGPointMake(0, 4))
        bezierPath.addCurveToPoint(CGPointMake(4, 2), controlPoint1: CGPointMake(2, 2), controlPoint2: CGPointMake(4, 2))
        bezierPath.addLineToPoint(CGPointMake(5, 2))
        bezierPath.addLineToPoint(CGPointMake(5, 2))
        bezierPath.closePath()
        color.setFill()
        bezierPath.fill()


        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRectMake(6, 0, 2, 5))
        color.setFill()
        rectanglePath.fill()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: CGRectMake(18, 0, 2, 5))
        color.setFill()
        rectangle2Path.fill()


        //// Bezier 3 Drawing
        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(22.62, 9.15))
        bezier3Path.addLineToPoint(CGPointMake(3.38, 9.15))
        bezier3Path.addLineToPoint(CGPointMake(3.38, 22.62))
        bezier3Path.addLineToPoint(CGPointMake(22.62, 22.62))
        bezier3Path.addLineToPoint(CGPointMake(22.62, 9.15))
        bezier3Path.closePath()
        color.setStroke()
        bezier3Path.lineWidth = 1
        bezier3Path.stroke()
    }

    public class func drawScheduletabgrey() {

        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(6.27, 5.31))
        bezierPath.addLineToPoint(CGPointMake(8.19, 5.31))
        bezierPath.addLineToPoint(CGPointMake(8.19, 0.5))
        bezierPath.addLineToPoint(CGPointMake(6.27, 0.5))
        bezierPath.addLineToPoint(CGPointMake(6.27, 5.31))
        bezierPath.closePath()
        bezierPath.lineCapStyle = kCGLineCapRound;

        Assets.lightGrey.setFill()
        bezierPath.fill()


        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(17.81, 5.31))
        bezier2Path.addLineToPoint(CGPointMake(19.73, 5.31))
        bezier2Path.addLineToPoint(CGPointMake(19.73, 0.5))
        bezier2Path.addLineToPoint(CGPointMake(17.81, 0.5))
        bezier2Path.addLineToPoint(CGPointMake(17.81, 5.31))
        bezier2Path.closePath()
        bezier2Path.lineCapStyle = kCGLineCapRound;

        Assets.lightGrey.setFill()
        bezier2Path.fill()


        //// Bezier 3 Drawing
        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(22.62, 9.15))
        bezier3Path.addLineToPoint(CGPointMake(3.38, 9.15))
        bezier3Path.addLineToPoint(CGPointMake(3.38, 22.62))
        bezier3Path.addLineToPoint(CGPointMake(22.62, 22.62))
        bezier3Path.addLineToPoint(CGPointMake(22.62, 9.15))
        bezier3Path.closePath()
        Assets.lightGrey.setStroke()
        bezier3Path.lineWidth = 1
        bezier3Path.stroke()


        //// Bezier 4 Drawing
        var bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(0.5, 6.27))
        bezier4Path.addCurveToPoint(CGPointMake(1.46, 3.38), controlPoint1: CGPointMake(0.5, 6.27), controlPoint2: CGPointMake(0.5, 4.35))
        bezier4Path.addCurveToPoint(CGPointMake(4.35, 2.42), controlPoint1: CGPointMake(2.42, 2.42), controlPoint2: CGPointMake(4.35, 2.42))
        bezier4Path.moveToPoint(CGPointMake(21.65, 2.42))
        bezier4Path.addCurveToPoint(CGPointMake(24.54, 3.38), controlPoint1: CGPointMake(21.65, 2.42), controlPoint2: CGPointMake(23.58, 2.42))
        bezier4Path.addCurveToPoint(CGPointMake(25.5, 6.27), controlPoint1: CGPointMake(25.5, 4.35), controlPoint2: CGPointMake(25.5, 6.27))
        bezier4Path.addLineToPoint(CGPointMake(25.5, 22.62))
        bezier4Path.addCurveToPoint(CGPointMake(24.54, 24.54), controlPoint1: CGPointMake(25.5, 22.62), controlPoint2: CGPointMake(25.26, 23.82))
        bezier4Path.addCurveToPoint(CGPointMake(22.62, 25.5), controlPoint1: CGPointMake(23.82, 25.26), controlPoint2: CGPointMake(22.62, 25.5))
        bezier4Path.addLineToPoint(CGPointMake(3.38, 25.5))
        bezier4Path.addCurveToPoint(CGPointMake(1.46, 24.54), controlPoint1: CGPointMake(3.38, 25.5), controlPoint2: CGPointMake(2.18, 25.26))
        bezier4Path.addCurveToPoint(CGPointMake(0.5, 22.62), controlPoint1: CGPointMake(0.74, 23.82), controlPoint2: CGPointMake(0.5, 22.62))
        bezier4Path.addLineToPoint(CGPointMake(0.5, 6.27))
        bezier4Path.moveToPoint(CGPointMake(4.35, 2.42))
        bezier4Path.addLineToPoint(CGPointMake(5.31, 2.42))
        bezier4Path.addLineToPoint(CGPointMake(5.31, 2.43))
        bezier4Path.addCurveToPoint(CGPointMake(5.31, 5.31), controlPoint1: CGPointMake(5.31, 2.42), controlPoint2: CGPointMake(5.31, 5.31))
        bezier4Path.addCurveToPoint(CGPointMake(6.27, 6.27), controlPoint1: CGPointMake(5.31, 5.31), controlPoint2: CGPointMake(5.55, 6.03))
        bezier4Path.addCurveToPoint(CGPointMake(8.19, 6.27), controlPoint1: CGPointMake(6.99, 6.51), controlPoint2: CGPointMake(7.47, 6.51))
        bezier4Path.addCurveToPoint(CGPointMake(9.15, 5.31), controlPoint1: CGPointMake(8.91, 6.03), controlPoint2: CGPointMake(9.15, 5.31))
        bezier4Path.addLineToPoint(CGPointMake(9.15, 2.42))
        bezier4Path.addLineToPoint(CGPointMake(16.85, 2.42))
        bezier4Path.addLineToPoint(CGPointMake(16.85, 5.31))
        bezier4Path.addCurveToPoint(CGPointMake(17.81, 6.27), controlPoint1: CGPointMake(16.85, 5.31), controlPoint2: CGPointMake(17.09, 6.03))
        bezier4Path.addCurveToPoint(CGPointMake(18.82, 6.45), controlPoint1: CGPointMake(18.19, 6.4), controlPoint2: CGPointMake(18.82, 6.45))
        bezier4Path.addCurveToPoint(CGPointMake(19.73, 6.27), controlPoint1: CGPointMake(18.82, 6.45), controlPoint2: CGPointMake(19.39, 6.38))
        bezier4Path.addCurveToPoint(CGPointMake(20.69, 5.31), controlPoint1: CGPointMake(20.45, 6.03), controlPoint2: CGPointMake(20.69, 5.31))
        bezier4Path.addLineToPoint(CGPointMake(20.69, 2.42))
        bezier4Path.addLineToPoint(CGPointMake(21.65, 2.42))
        Assets.lightGrey.setStroke()
        bezier4Path.lineWidth = 1
        bezier4Path.stroke()
    }

    public class func drawPrintertabselected() {
        //// Color Declarations
        let color = UIColor(red: 0.969, green: 0.498, blue: 0.000, alpha: 1.000)

        //// Bezier 4 Drawing
        var bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(6.74, 0.52))
        bezier4Path.addCurveToPoint(CGPointMake(4.31, 2.52), controlPoint1: CGPointMake(5.61, 0.65), controlPoint2: CGPointMake(4.66, 1.43))
        bezier4Path.addCurveToPoint(CGPointMake(4.15, 5.7), controlPoint1: CGPointMake(4.16, 3), controlPoint2: CGPointMake(4.15, 3.08))
        bezier4Path.addLineToPoint(CGPointMake(4.15, 8.12))
        bezier4Path.addLineToPoint(CGPointMake(4.08, 8.16))
        bezier4Path.addCurveToPoint(CGPointMake(3.69, 8.19), controlPoint1: CGPointMake(4.02, 8.2), controlPoint2: CGPointMake(3.96, 8.21))
        bezier4Path.addCurveToPoint(CGPointMake(1.56, 8.7), controlPoint1: CGPointMake(2.85, 8.15), controlPoint2: CGPointMake(2.14, 8.32))
        bezier4Path.addCurveToPoint(CGPointMake(0.82, 9.44), controlPoint1: CGPointMake(1.33, 8.85), controlPoint2: CGPointMake(0.96, 9.22))
        bezier4Path.addCurveToPoint(CGPointMake(0.32, 10.64), controlPoint1: CGPointMake(0.59, 9.79), controlPoint2: CGPointMake(0.4, 10.25))
        bezier4Path.addCurveToPoint(CGPointMake(0.3, 14.08), controlPoint1: CGPointMake(0.3, 10.75), controlPoint2: CGPointMake(0.3, 11.79))
        bezier4Path.addCurveToPoint(CGPointMake(0.37, 17.56), controlPoint1: CGPointMake(0.31, 17.33), controlPoint2: CGPointMake(0.31, 17.35))
        bezier4Path.addCurveToPoint(CGPointMake(1.09, 18.82), controlPoint1: CGPointMake(0.52, 18.07), controlPoint2: CGPointMake(0.74, 18.46))
        bezier4Path.addCurveToPoint(CGPointMake(2.41, 19.63), controlPoint1: CGPointMake(1.48, 19.23), controlPoint2: CGPointMake(1.88, 19.48))
        bezier4Path.addCurveToPoint(CGPointMake(3.64, 19.76), controlPoint1: CGPointMake(2.73, 19.72), controlPoint2: CGPointMake(3.09, 19.76))
        bezier4Path.addCurveToPoint(CGPointMake(4.12, 19.79), controlPoint1: CGPointMake(3.95, 19.76), controlPoint2: CGPointMake(4.1, 19.77))
        bezier4Path.addCurveToPoint(CGPointMake(4.15, 21.26), controlPoint1: CGPointMake(4.14, 19.81), controlPoint2: CGPointMake(4.15, 20.18))
        bezier4Path.addCurveToPoint(CGPointMake(4.28, 23.43), controlPoint1: CGPointMake(4.15, 22.78), controlPoint2: CGPointMake(4.17, 23.04))
        bezier4Path.addCurveToPoint(CGPointMake(5.02, 24.66), controlPoint1: CGPointMake(4.42, 23.92), controlPoint2: CGPointMake(4.64, 24.28))
        bezier4Path.addCurveToPoint(CGPointMake(6.73, 25.49), controlPoint1: CGPointMake(5.51, 25.14), controlPoint2: CGPointMake(6.05, 25.41))
        bezier4Path.addCurveToPoint(CGPointMake(19.09, 25.49), controlPoint1: CGPointMake(7.07, 25.53), controlPoint2: CGPointMake(18.76, 25.53))
        bezier4Path.addCurveToPoint(CGPointMake(21.48, 23.63), controlPoint1: CGPointMake(20.19, 25.36), controlPoint2: CGPointMake(21.1, 24.65))
        bezier4Path.addCurveToPoint(CGPointMake(21.68, 21.38), controlPoint1: CGPointMake(21.67, 23.14), controlPoint2: CGPointMake(21.67, 23.11))
        bezier4Path.addCurveToPoint(CGPointMake(21.7, 19.78), controlPoint1: CGPointMake(21.68, 20.52), controlPoint2: CGPointMake(21.69, 19.8))
        bezier4Path.addCurveToPoint(CGPointMake(22.25, 19.76), controlPoint1: CGPointMake(21.72, 19.77), controlPoint2: CGPointMake(21.92, 19.76))
        bezier4Path.addCurveToPoint(CGPointMake(23.57, 19.58), controlPoint1: CGPointMake(22.91, 19.76), controlPoint2: CGPointMake(23.13, 19.73))
        bezier4Path.addCurveToPoint(CGPointMake(24.92, 18.69), controlPoint1: CGPointMake(24.13, 19.4), controlPoint2: CGPointMake(24.58, 19.1))
        bezier4Path.addCurveToPoint(CGPointMake(25.55, 17.33), controlPoint1: CGPointMake(25.2, 18.34), controlPoint2: CGPointMake(25.36, 17.99))
        bezier4Path.addCurveToPoint(CGPointMake(25.57, 13.92), controlPoint1: CGPointMake(25.57, 17.27), controlPoint2: CGPointMake(25.57, 16.04))
        bezier4Path.addCurveToPoint(CGPointMake(25.37, 10.04), controlPoint1: CGPointMake(25.56, 10.24), controlPoint2: CGPointMake(25.58, 10.59))
        bezier4Path.addCurveToPoint(CGPointMake(24.05, 8.55), controlPoint1: CGPointMake(25.12, 9.4), controlPoint2: CGPointMake(24.65, 8.86))
        bezier4Path.addCurveToPoint(CGPointMake(22.33, 8.2), controlPoint1: CGPointMake(23.54, 8.29), controlPoint2: CGPointMake(23.11, 8.2))
        bezier4Path.addCurveToPoint(CGPointMake(21.73, 8.16), controlPoint1: CGPointMake(21.9, 8.2), controlPoint2: CGPointMake(21.77, 8.19))
        bezier4Path.addCurveToPoint(CGPointMake(21.68, 5.91), controlPoint1: CGPointMake(21.68, 8.12), controlPoint2: CGPointMake(21.68, 8.07))
        bezier4Path.addCurveToPoint(CGPointMake(21.66, 3.31), controlPoint1: CGPointMake(21.69, 4.55), controlPoint2: CGPointMake(21.68, 3.55))
        bezier4Path.addCurveToPoint(CGPointMake(20.8, 1.35), controlPoint1: CGPointMake(21.6, 2.45), controlPoint2: CGPointMake(21.34, 1.87))
        bezier4Path.addCurveToPoint(CGPointMake(19.21, 0.54), controlPoint1: CGPointMake(20.35, 0.92), controlPoint2: CGPointMake(19.8, 0.64))
        bezier4Path.addCurveToPoint(CGPointMake(6.74, 0.52), controlPoint1: CGPointMake(18.99, 0.5), controlPoint2: CGPointMake(7.07, 0.48))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(19.14, 2.53))
        bezier4Path.addCurveToPoint(CGPointMake(19.69, 3.27), controlPoint1: CGPointMake(19.46, 2.67), controlPoint2: CGPointMake(19.63, 2.91))
        bezier4Path.addCurveToPoint(CGPointMake(19.72, 5.76), controlPoint1: CGPointMake(19.71, 3.39), controlPoint2: CGPointMake(19.72, 4.28))
        bezier4Path.addCurveToPoint(CGPointMake(19.67, 8.12), controlPoint1: CGPointMake(19.72, 7.87), controlPoint2: CGPointMake(19.72, 8.08))
        bezier4Path.addCurveToPoint(CGPointMake(12.92, 8.17), controlPoint1: CGPointMake(19.63, 8.17), controlPoint2: CGPointMake(19.38, 8.17))
        bezier4Path.addCurveToPoint(CGPointMake(6.17, 8.12), controlPoint1: CGPointMake(6.42, 8.17), controlPoint2: CGPointMake(6.22, 8.17))
        bezier4Path.addCurveToPoint(CGPointMake(6.13, 5.62), controlPoint1: CGPointMake(6.13, 8.07), controlPoint2: CGPointMake(6.12, 7.88))
        bezier4Path.addLineToPoint(CGPointMake(6.14, 3.18))
        bezier4Path.addLineToPoint(CGPointMake(6.22, 3))
        bezier4Path.addCurveToPoint(CGPointMake(6.87, 2.46), controlPoint1: CGPointMake(6.34, 2.73), controlPoint2: CGPointMake(6.58, 2.54))
        bezier4Path.addCurveToPoint(CGPointMake(12.96, 2.45), controlPoint1: CGPointMake(6.92, 2.45), controlPoint2: CGPointMake(9.66, 2.45))
        bezier4Path.addLineToPoint(CGPointMake(18.97, 2.45))
        bezier4Path.addLineToPoint(CGPointMake(19.14, 2.53))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(21.65, 10.21))
        bezier4Path.addCurveToPoint(CGPointMake(22.49, 10.92), controlPoint1: CGPointMake(21.99, 10.31), controlPoint2: CGPointMake(22.33, 10.6))
        bezier4Path.addCurveToPoint(CGPointMake(22.22, 12.57), controlPoint1: CGPointMake(22.77, 11.47), controlPoint2: CGPointMake(22.67, 12.13))
        bezier4Path.addCurveToPoint(CGPointMake(21.19, 12.99), controlPoint1: CGPointMake(21.94, 12.85), controlPoint2: CGPointMake(21.6, 12.99))
        bezier4Path.addCurveToPoint(CGPointMake(20.23, 12.62), controlPoint1: CGPointMake(20.82, 12.99), controlPoint2: CGPointMake(20.5, 12.87))
        bezier4Path.addCurveToPoint(CGPointMake(19.9, 10.94), controlPoint1: CGPointMake(19.75, 12.17), controlPoint2: CGPointMake(19.62, 11.52))
        bezier4Path.addCurveToPoint(CGPointMake(21.65, 10.21), controlPoint1: CGPointMake(20.22, 10.29), controlPoint2: CGPointMake(20.94, 9.99))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(19.68, 15.01))
        bezier4Path.addCurveToPoint(CGPointMake(19.72, 18.81), controlPoint1: CGPointMake(19.71, 15.05), controlPoint2: CGPointMake(19.72, 15.62))
        bezier4Path.addCurveToPoint(CGPointMake(19.69, 22.74), controlPoint1: CGPointMake(19.72, 21.28), controlPoint2: CGPointMake(19.71, 22.62))
        bezier4Path.addCurveToPoint(CGPointMake(19.13, 23.49), controlPoint1: CGPointMake(19.63, 23.11), controlPoint2: CGPointMake(19.43, 23.37))
        bezier4Path.addLineToPoint(CGPointMake(18.97, 23.55))
        bezier4Path.addLineToPoint(CGPointMake(15.93, 23.57))
        bezier4Path.addCurveToPoint(CGPointMake(9.87, 23.57), controlPoint1: CGPointMake(14.26, 23.58), controlPoint2: CGPointMake(11.53, 23.58))
        bezier4Path.addLineToPoint(CGPointMake(6.84, 23.56))
        bezier4Path.addLineToPoint(CGPointMake(6.65, 23.46))
        bezier4Path.addCurveToPoint(CGPointMake(6.2, 22.99), controlPoint1: CGPointMake(6.43, 23.36), controlPoint2: CGPointMake(6.29, 23.21))
        bezier4Path.addLineToPoint(CGPointMake(6.14, 22.83))
        bezier4Path.addLineToPoint(CGPointMake(6.14, 18.92))
        bezier4Path.addLineToPoint(CGPointMake(6.14, 15.01))
        bezier4Path.addLineToPoint(CGPointMake(6.21, 14.98))
        bezier4Path.addCurveToPoint(CGPointMake(12.96, 14.95), controlPoint1: CGPointMake(6.26, 14.95), controlPoint2: CGPointMake(7.61, 14.94))
        bezier4Path.addCurveToPoint(CGPointMake(19.68, 15.01), controlPoint1: CGPointMake(19.54, 14.95), controlPoint2: CGPointMake(19.64, 14.95))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(8.11, 16.92))
        bezier4Path.addCurveToPoint(CGPointMake(8.11, 18.74), controlPoint1: CGPointMake(8.04, 17.02), controlPoint2: CGPointMake(8.04, 18.67))
        bezier4Path.addCurveToPoint(CGPointMake(12.92, 18.78), controlPoint1: CGPointMake(8.15, 18.78), controlPoint2: CGPointMake(8.63, 18.78))
        bezier4Path.addCurveToPoint(CGPointMake(17.75, 18.73), controlPoint1: CGPointMake(17.66, 18.78), controlPoint2: CGPointMake(17.69, 18.78))
        bezier4Path.addCurveToPoint(CGPointMake(17.8, 17.81), controlPoint1: CGPointMake(17.8, 18.67), controlPoint2: CGPointMake(17.8, 18.63))
        bezier4Path.addCurveToPoint(CGPointMake(17.76, 16.91), controlPoint1: CGPointMake(17.8, 17.06), controlPoint2: CGPointMake(17.8, 16.94))
        bezier4Path.addCurveToPoint(CGPointMake(12.93, 16.86), controlPoint1: CGPointMake(17.72, 16.87), controlPoint2: CGPointMake(17.24, 16.86))
        bezier4Path.addLineToPoint(CGPointMake(8.15, 16.86))
        bezier4Path.addLineToPoint(CGPointMake(8.11, 16.92))
        bezier4Path.closePath()
        bezier4Path.moveToPoint(CGPointMake(8.13, 19.77))
        bezier4Path.addCurveToPoint(CGPointMake(8.06, 20.69), controlPoint1: CGPointMake(8.06, 19.81), controlPoint2: CGPointMake(8.06, 19.82))
        bezier4Path.addCurveToPoint(CGPointMake(8.1, 21.61), controlPoint1: CGPointMake(8.06, 21.39), controlPoint2: CGPointMake(8.07, 21.57))
        bezier4Path.addCurveToPoint(CGPointMake(11.43, 21.67), controlPoint1: CGPointMake(8.14, 21.66), controlPoint2: CGPointMake(8.21, 21.66))
        bezier4Path.addCurveToPoint(CGPointMake(14.79, 21.64), controlPoint1: CGPointMake(14.05, 21.67), controlPoint2: CGPointMake(14.74, 21.67))
        bezier4Path.addLineToPoint(CGPointMake(14.86, 21.6))
        bezier4Path.addLineToPoint(CGPointMake(14.87, 20.7))
        bezier4Path.addCurveToPoint(CGPointMake(14.83, 19.76), controlPoint1: CGPointMake(14.88, 19.88), controlPoint2: CGPointMake(14.87, 19.8))
        bezier4Path.addCurveToPoint(CGPointMake(11.49, 19.73), controlPoint1: CGPointMake(14.79, 19.74), controlPoint2: CGPointMake(14.08, 19.73))
        bezier4Path.addCurveToPoint(CGPointMake(8.13, 19.77), controlPoint1: CGPointMake(8.55, 19.73), controlPoint2: CGPointMake(8.18, 19.73))
        bezier4Path.closePath()
        color.setFill()
        bezier4Path.fill()
    }

    public class func drawPrintertabgrey() {

        //// Bezier 4 Drawing
        var bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(6.99, 1.02))
        bezier4Path.addCurveToPoint(CGPointMake(4.65, 2.94), controlPoint1: CGPointMake(5.9, 1.14), controlPoint2: CGPointMake(4.98, 1.9))
        bezier4Path.addCurveToPoint(CGPointMake(4.5, 5.99), controlPoint1: CGPointMake(4.5, 3.4), controlPoint2: CGPointMake(4.5, 3.48))
        bezier4Path.addLineToPoint(CGPointMake(4.5, 8.31))
        bezier4Path.addLineToPoint(CGPointMake(4.43, 8.36))
        bezier4Path.addCurveToPoint(CGPointMake(4.06, 8.39), controlPoint1: CGPointMake(4.37, 8.39), controlPoint2: CGPointMake(4.32, 8.4))
        bezier4Path.addCurveToPoint(CGPointMake(2.01, 8.88), controlPoint1: CGPointMake(3.25, 8.34), controlPoint2: CGPointMake(2.56, 8.51))
        bezier4Path.addCurveToPoint(CGPointMake(1.3, 9.58), controlPoint1: CGPointMake(1.79, 9.02), controlPoint2: CGPointMake(1.44, 9.37))
        bezier4Path.addCurveToPoint(CGPointMake(0.82, 10.73), controlPoint1: CGPointMake(1.07, 9.91), controlPoint2: CGPointMake(0.89, 10.36))
        bezier4Path.addCurveToPoint(CGPointMake(0.8, 14.03), controlPoint1: CGPointMake(0.8, 10.85), controlPoint2: CGPointMake(0.8, 11.83))
        bezier4Path.addCurveToPoint(CGPointMake(0.87, 17.38), controlPoint1: CGPointMake(0.81, 17.16), controlPoint2: CGPointMake(0.81, 17.17))
        bezier4Path.addCurveToPoint(CGPointMake(1.56, 18.59), controlPoint1: CGPointMake(1.01, 17.87), controlPoint2: CGPointMake(1.23, 18.24))
        bezier4Path.addCurveToPoint(CGPointMake(2.83, 19.36), controlPoint1: CGPointMake(1.93, 18.98), controlPoint2: CGPointMake(2.32, 19.22))
        bezier4Path.addCurveToPoint(CGPointMake(4.01, 19.49), controlPoint1: CGPointMake(3.13, 19.45), controlPoint2: CGPointMake(3.48, 19.49))
        bezier4Path.addCurveToPoint(CGPointMake(4.47, 19.52), controlPoint1: CGPointMake(4.3, 19.49), controlPoint2: CGPointMake(4.45, 19.5))
        bezier4Path.addCurveToPoint(CGPointMake(4.5, 20.93), controlPoint1: CGPointMake(4.49, 19.54), controlPoint2: CGPointMake(4.5, 19.89))
        bezier4Path.addCurveToPoint(CGPointMake(4.62, 23.01), controlPoint1: CGPointMake(4.5, 22.39), controlPoint2: CGPointMake(4.51, 22.64))
        bezier4Path.addCurveToPoint(CGPointMake(5.34, 24.19), controlPoint1: CGPointMake(4.76, 23.48), controlPoint2: CGPointMake(4.97, 23.83))
        bezier4Path.addCurveToPoint(CGPointMake(6.97, 24.99), controlPoint1: CGPointMake(5.81, 24.66), controlPoint2: CGPointMake(6.32, 24.91))
        bezier4Path.addCurveToPoint(CGPointMake(18.85, 24.99), controlPoint1: CGPointMake(7.3, 25.03), controlPoint2: CGPointMake(18.53, 25.03))
        bezier4Path.addCurveToPoint(CGPointMake(21.14, 23.2), controlPoint1: CGPointMake(19.9, 24.86), controlPoint2: CGPointMake(20.77, 24.19))
        bezier4Path.addCurveToPoint(CGPointMake(21.33, 21.05), controlPoint1: CGPointMake(21.32, 22.73), controlPoint2: CGPointMake(21.32, 22.7))
        bezier4Path.addCurveToPoint(CGPointMake(21.36, 19.51), controlPoint1: CGPointMake(21.34, 20.22), controlPoint2: CGPointMake(21.35, 19.53))
        bezier4Path.addCurveToPoint(CGPointMake(21.88, 19.49), controlPoint1: CGPointMake(21.37, 19.5), controlPoint2: CGPointMake(21.56, 19.49))
        bezier4Path.addCurveToPoint(CGPointMake(23.15, 19.32), controlPoint1: CGPointMake(22.52, 19.49), controlPoint2: CGPointMake(22.73, 19.46))
        bezier4Path.addCurveToPoint(CGPointMake(24.44, 18.46), controlPoint1: CGPointMake(23.69, 19.14), controlPoint2: CGPointMake(24.12, 18.86))
        bezier4Path.addCurveToPoint(CGPointMake(25.05, 17.16), controlPoint1: CGPointMake(24.71, 18.13), controlPoint2: CGPointMake(24.87, 17.79))
        bezier4Path.addCurveToPoint(CGPointMake(25.07, 13.89), controlPoint1: CGPointMake(25.07, 17.1), controlPoint2: CGPointMake(25.07, 15.92))
        bezier4Path.addCurveToPoint(CGPointMake(24.87, 10.16), controlPoint1: CGPointMake(25.06, 10.35), controlPoint2: CGPointMake(25.08, 10.69))
        bezier4Path.addCurveToPoint(CGPointMake(23.61, 8.73), controlPoint1: CGPointMake(24.64, 9.54), controlPoint2: CGPointMake(24.19, 9.03))
        bezier4Path.addCurveToPoint(CGPointMake(21.95, 8.39), controlPoint1: CGPointMake(23.12, 8.48), controlPoint2: CGPointMake(22.71, 8.39))
        bezier4Path.addCurveToPoint(CGPointMake(21.38, 8.36), controlPoint1: CGPointMake(21.55, 8.39), controlPoint2: CGPointMake(21.42, 8.39))
        bezier4Path.addCurveToPoint(CGPointMake(21.34, 6.2), controlPoint1: CGPointMake(21.33, 8.32), controlPoint2: CGPointMake(21.33, 8.27))
        bezier4Path.addCurveToPoint(CGPointMake(21.32, 3.7), controlPoint1: CGPointMake(21.34, 4.89), controlPoint2: CGPointMake(21.34, 3.93))
        bezier4Path.addCurveToPoint(CGPointMake(20.49, 1.82), controlPoint1: CGPointMake(21.26, 2.87), controlPoint2: CGPointMake(21.01, 2.32))
        bezier4Path.addCurveToPoint(CGPointMake(18.96, 1.04), controlPoint1: CGPointMake(20.06, 1.4), controlPoint2: CGPointMake(19.53, 1.13))
        bezier4Path.addCurveToPoint(CGPointMake(6.99, 1.02), controlPoint1: CGPointMake(18.75, 1), controlPoint2: CGPointMake(7.3, 0.98))
        bezier4Path.closePath()
        Assets.lightGrey.setStroke()
        bezier4Path.lineWidth = 1
        bezier4Path.stroke()


        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(18.9, 2.95))
        bezierPath.addCurveToPoint(CGPointMake(19.42, 3.66), controlPoint1: CGPointMake(19.2, 3.09), controlPoint2: CGPointMake(19.36, 3.31))
        bezierPath.addCurveToPoint(CGPointMake(19.45, 6.05), controlPoint1: CGPointMake(19.44, 3.78), controlPoint2: CGPointMake(19.45, 4.63))
        bezierPath.addCurveToPoint(CGPointMake(19.4, 8.32), controlPoint1: CGPointMake(19.45, 8.08), controlPoint2: CGPointMake(19.45, 8.27))
        bezierPath.addCurveToPoint(CGPointMake(12.92, 8.37), controlPoint1: CGPointMake(19.36, 8.36), controlPoint2: CGPointMake(19.13, 8.37))
        bezierPath.addCurveToPoint(CGPointMake(6.44, 8.32), controlPoint1: CGPointMake(6.68, 8.37), controlPoint2: CGPointMake(6.48, 8.36))
        bezierPath.addCurveToPoint(CGPointMake(6.4, 5.92), controlPoint1: CGPointMake(6.39, 8.27), controlPoint2: CGPointMake(6.39, 8.09))
        bezierPath.addLineToPoint(CGPointMake(6.41, 3.57))
        bezierPath.addLineToPoint(CGPointMake(6.48, 3.4))
        bezierPath.addCurveToPoint(CGPointMake(7.11, 2.88), controlPoint1: CGPointMake(6.6, 3.14), controlPoint2: CGPointMake(6.84, 2.95))
        bezierPath.addCurveToPoint(CGPointMake(12.96, 2.87), controlPoint1: CGPointMake(7.15, 2.87), controlPoint2: CGPointMake(9.79, 2.87))
        bezierPath.addLineToPoint(CGPointMake(18.73, 2.87))
        bezierPath.addLineToPoint(CGPointMake(18.9, 2.95))
        bezierPath.closePath()
        Assets.lightGrey.setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()


        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(21.31, 10.32))
        bezier2Path.addCurveToPoint(CGPointMake(22.11, 11), controlPoint1: CGPointMake(21.63, 10.42), controlPoint2: CGPointMake(21.96, 10.7))
        bezier2Path.addCurveToPoint(CGPointMake(21.85, 12.59), controlPoint1: CGPointMake(22.38, 11.53), controlPoint2: CGPointMake(22.28, 12.17))
        bezier2Path.addCurveToPoint(CGPointMake(20.87, 12.99), controlPoint1: CGPointMake(21.58, 12.86), controlPoint2: CGPointMake(21.26, 12.99))
        bezier2Path.addCurveToPoint(CGPointMake(19.94, 12.63), controlPoint1: CGPointMake(20.51, 12.99), controlPoint2: CGPointMake(20.2, 12.87))
        bezier2Path.addCurveToPoint(CGPointMake(19.63, 11.03), controlPoint1: CGPointMake(19.48, 12.2), controlPoint2: CGPointMake(19.36, 11.58))
        bezier2Path.addCurveToPoint(CGPointMake(21.31, 10.32), controlPoint1: CGPointMake(19.93, 10.4), controlPoint2: CGPointMake(20.62, 10.11))
        bezier2Path.closePath()
        Assets.lightGrey.setStroke()
        bezier2Path.lineWidth = 1
        bezier2Path.stroke()


        //// Bezier 3 Drawing
        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(19.41, 14.93))
        bezier3Path.addCurveToPoint(CGPointMake(19.45, 18.58), controlPoint1: CGPointMake(19.45, 14.97), controlPoint2: CGPointMake(19.45, 15.51))
        bezier3Path.addCurveToPoint(CGPointMake(19.42, 22.35), controlPoint1: CGPointMake(19.45, 20.95), controlPoint2: CGPointMake(19.44, 22.23))
        bezier3Path.addCurveToPoint(CGPointMake(18.89, 23.07), controlPoint1: CGPointMake(19.36, 22.7), controlPoint2: CGPointMake(19.18, 22.96))
        bezier3Path.addLineToPoint(CGPointMake(18.73, 23.13))
        bezier3Path.addLineToPoint(CGPointMake(15.81, 23.15))
        bezier3Path.addCurveToPoint(CGPointMake(9.99, 23.15), controlPoint1: CGPointMake(14.21, 23.16), controlPoint2: CGPointMake(11.59, 23.16))
        bezier3Path.addLineToPoint(CGPointMake(7.08, 23.14))
        bezier3Path.addLineToPoint(CGPointMake(6.9, 23.05))
        bezier3Path.addCurveToPoint(CGPointMake(6.47, 22.59), controlPoint1: CGPointMake(6.69, 22.95), controlPoint2: CGPointMake(6.55, 22.8))
        bezier3Path.addLineToPoint(CGPointMake(6.41, 22.44))
        bezier3Path.addLineToPoint(CGPointMake(6.41, 18.68))
        bezier3Path.addLineToPoint(CGPointMake(6.41, 14.93))
        bezier3Path.addLineToPoint(CGPointMake(6.47, 14.9))
        bezier3Path.addCurveToPoint(CGPointMake(12.96, 14.87), controlPoint1: CGPointMake(6.53, 14.87), controlPoint2: CGPointMake(7.82, 14.87))
        bezier3Path.addCurveToPoint(CGPointMake(19.41, 14.93), controlPoint1: CGPointMake(19.27, 14.88), controlPoint2: CGPointMake(19.38, 14.88))
        bezier3Path.closePath()
        Assets.lightGrey.setStroke()
        bezier3Path.lineWidth = 1
        bezier3Path.stroke()


        //// Bezier 5 Drawing
        var bezier5Path = UIBezierPath()
        bezier5Path.moveToPoint(CGPointMake(8.3, 16.77))
        bezier5Path.addCurveToPoint(CGPointMake(8.3, 18.51), controlPoint1: CGPointMake(8.24, 16.86), controlPoint2: CGPointMake(8.24, 18.45))
        bezier5Path.addCurveToPoint(CGPointMake(12.92, 18.55), controlPoint1: CGPointMake(8.34, 18.55), controlPoint2: CGPointMake(8.8, 18.55))
        bezier5Path.addCurveToPoint(CGPointMake(17.56, 18.5), controlPoint1: CGPointMake(17.47, 18.55), controlPoint2: CGPointMake(17.5, 18.55))
        bezier5Path.addCurveToPoint(CGPointMake(17.61, 17.62), controlPoint1: CGPointMake(17.61, 18.45), controlPoint2: CGPointMake(17.61, 18.41))
        bezier5Path.addCurveToPoint(CGPointMake(17.57, 16.75), controlPoint1: CGPointMake(17.61, 16.9), controlPoint2: CGPointMake(17.61, 16.78))
        bezier5Path.addCurveToPoint(CGPointMake(12.93, 16.71), controlPoint1: CGPointMake(17.53, 16.71), controlPoint2: CGPointMake(17.07, 16.71))
        bezier5Path.addLineToPoint(CGPointMake(8.34, 16.71))
        bezier5Path.addLineToPoint(CGPointMake(8.3, 16.77))
        bezier5Path.closePath()
        Assets.lightGrey.setFill()
        bezier5Path.fill()
        Assets.lightGrey.setStroke()
        bezier5Path.lineWidth = 0
        bezier5Path.stroke()


        //// Bezier 6 Drawing
        var bezier6Path = UIBezierPath()
        bezier6Path.moveToPoint(CGPointMake(8.32, 19.5))
        bezier6Path.addCurveToPoint(CGPointMake(8.26, 20.38), controlPoint1: CGPointMake(8.26, 19.54), controlPoint2: CGPointMake(8.26, 19.55))
        bezier6Path.addCurveToPoint(CGPointMake(8.3, 21.27), controlPoint1: CGPointMake(8.26, 21.06), controlPoint2: CGPointMake(8.27, 21.22))
        bezier6Path.addCurveToPoint(CGPointMake(11.49, 21.32), controlPoint1: CGPointMake(8.33, 21.32), controlPoint2: CGPointMake(8.4, 21.32))
        bezier6Path.addCurveToPoint(CGPointMake(14.72, 21.3), controlPoint1: CGPointMake(14.01, 21.33), controlPoint2: CGPointMake(14.67, 21.32))
        bezier6Path.addLineToPoint(CGPointMake(14.79, 21.26))
        bezier6Path.addLineToPoint(CGPointMake(14.8, 20.4))
        bezier6Path.addCurveToPoint(CGPointMake(14.75, 19.49), controlPoint1: CGPointMake(14.8, 19.6), controlPoint2: CGPointMake(14.8, 19.52))
        bezier6Path.addCurveToPoint(CGPointMake(11.54, 19.46), controlPoint1: CGPointMake(14.72, 19.47), controlPoint2: CGPointMake(14.03, 19.46))
        bezier6Path.addCurveToPoint(CGPointMake(8.32, 19.5), controlPoint1: CGPointMake(8.72, 19.46), controlPoint2: CGPointMake(8.37, 19.47))
        bezier6Path.closePath()
        Assets.lightGrey.setFill()
        bezier6Path.fill()
        Assets.lightGrey.setStroke()
        bezier6Path.lineWidth = 0
        bezier6Path.stroke()
    }

    public class func drawRedstatus() {

        //// Oval Drawing
        var ovalPath = UIBezierPath(ovalInRect: CGRectMake(0, 0, 10, 10))
        Assets.red.setFill()
        ovalPath.fill()
    }

    public class func drawYellowstatus() {
        //// Color Declarations
        let yellowStatus = UIColor(red: 1.000, green: 0.857, blue: 0.000, alpha: 1.000)

        //// Oval Drawing
        var ovalPath = UIBezierPath(ovalInRect: CGRectMake(0, 0, 10, 10))
        yellowStatus.setFill()
        ovalPath.fill()
    }

    public class func drawGreenstatus() {
        //// Color Declarations
        let greenStatus = UIColor(red: 0.113, green: 0.804, blue: 0.216, alpha: 1.000)

        //// Oval Drawing
        var ovalPath = UIBezierPath(ovalInRect: CGRectMake(0, 0, 10, 10))
        greenStatus.setFill()
        ovalPath.fill()
    }

    public class func drawGreystatus() {

        //// Oval Drawing
        var ovalPath = UIBezierPath(ovalInRect: CGRectMake(0, 0, 10, 10))
        Assets.lightGrey.setFill()
        ovalPath.fill()
    }

    //// Generated Images

    public class var imageOfScheduletabselected: UIImage {
        if Cache.imageOfScheduletabselected != nil {
            return Cache.imageOfScheduletabselected!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(26, 26), false, 0)
            Assets.drawScheduletabselected()

        Cache.imageOfScheduletabselected = UIGraphicsGetImageFromCurrentImageContext()!.imageWithRenderingMode(UIImageRenderingMode.AlwaysOriginal)
        UIGraphicsEndImageContext()

        return Cache.imageOfScheduletabselected!
    }

    public class var imageOfScheduletabgrey: UIImage {
        if Cache.imageOfScheduletabgrey != nil {
            return Cache.imageOfScheduletabgrey!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(26, 26), false, 0)
            Assets.drawScheduletabgrey()

        Cache.imageOfScheduletabgrey = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfScheduletabgrey!
    }

    public class var imageOfPrintertabselected: UIImage {
        if Cache.imageOfPrintertabselected != nil {
            return Cache.imageOfPrintertabselected!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(26, 26), false, 0)
            Assets.drawPrintertabselected()

        Cache.imageOfPrintertabselected = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfPrintertabselected!
    }

    public class var imageOfPrintertabgrey: UIImage {
        if Cache.imageOfPrintertabgrey != nil {
            return Cache.imageOfPrintertabgrey!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(26, 26), false, 0)
            Assets.drawPrintertabgrey()

        Cache.imageOfPrintertabgrey = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfPrintertabgrey!
    }

    public class var imageOfRedstatus: UIImage {
        if Cache.imageOfRedstatus != nil {
            return Cache.imageOfRedstatus!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(10, 10), false, 0)
            Assets.drawRedstatus()

        Cache.imageOfRedstatus = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfRedstatus!
    }

    public class var imageOfYellowstatus: UIImage {
        if Cache.imageOfYellowstatus != nil {
            return Cache.imageOfYellowstatus!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(10, 10), false, 0)
            Assets.drawYellowstatus()

        Cache.imageOfYellowstatus = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfYellowstatus!
    }

    public class var imageOfGreenstatus: UIImage {
        if Cache.imageOfGreenstatus != nil {
            return Cache.imageOfGreenstatus!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(10, 10), false, 0)
            Assets.drawGreenstatus()

        Cache.imageOfGreenstatus = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfGreenstatus!
    }

    public class var imageOfGreystatus: UIImage {
        if Cache.imageOfGreystatus != nil {
            return Cache.imageOfGreystatus!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(10, 10), false, 0)
            Assets.drawGreystatus()

        Cache.imageOfGreystatus = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfGreystatus!
    }

    //// Customization Infrastructure

    @IBOutlet var scheduletabselectedTargets: [AnyObject]! {
        get { return Cache.scheduletabselectedTargets }
        set {
            Cache.scheduletabselectedTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(Assets.imageOfScheduletabselected)
            }
        }
    }

    @IBOutlet var scheduletabgreyTargets: [AnyObject]! {
        get { return Cache.scheduletabgreyTargets }
        set {
            Cache.scheduletabgreyTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(Assets.imageOfScheduletabgrey)
            }
        }
    }

    @IBOutlet var printertabselectedTargets: [AnyObject]! {
        get { return Cache.printertabselectedTargets }
        set {
            Cache.printertabselectedTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(Assets.imageOfPrintertabselected)
            }
        }
    }

    @IBOutlet var printertabgreyTargets: [AnyObject]! {
        get { return Cache.printertabgreyTargets }
        set {
            Cache.printertabgreyTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(Assets.imageOfPrintertabgrey)
            }
        }
    }

    @IBOutlet var redstatusTargets: [AnyObject]! {
        get { return Cache.redstatusTargets }
        set {
            Cache.redstatusTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(Assets.imageOfRedstatus)
            }
        }
    }

    @IBOutlet var yellowstatusTargets: [AnyObject]! {
        get { return Cache.yellowstatusTargets }
        set {
            Cache.yellowstatusTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(Assets.imageOfYellowstatus)
            }
        }
    }

    @IBOutlet var greenstatusTargets: [AnyObject]! {
        get { return Cache.greenstatusTargets }
        set {
            Cache.greenstatusTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(Assets.imageOfGreenstatus)
            }
        }
    }

    @IBOutlet var greystatusTargets: [AnyObject]! {
        get { return Cache.greystatusTargets }
        set {
            Cache.greystatusTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(Assets.imageOfGreystatus)
            }
        }
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
